### ISSUE TITLE
Warning: nil value is invalid, use ‘unspecified’ instead

### ISSUE THREAD

**Issue by jabotz** [doomemacs/themes#810] opened 2023-12-02 16:03 UTC
### Theme(s)

doom-nord-light

### What were you expecting?

No warnings

### What actually happened?

Warning: setting attribute ‘:background’ of face ‘font-lock-comment’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘region’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:background’ of face ‘font-lock-comment’: nil value is invalid, use ‘unspecified’ instead.

### Steps to reproduce

1. Run emacs 29.1
2. Switch to doom-nord-light theme
3. This can be fixed by changing lines 135 and 149 in `doom-nord-light-theme.el`

### Operating system

Windows 10, 11

### Emacs version

Emacs 29.1

### Installed commit of doom-themes

4aee1f5a0e54552669f747aa7c25e6027e73d76d

**Comment by jabotz** [comment] 2023-12-02 16:19
This is not a duplicate of [https://github.com/doomemacs/themes/issues/793](url), but a similar further issue.

**Comment by hlissner** [comment] 2023-12-02 17:06
This *is* a duplicate of #793, which covers all nil->unspecified warnings of this kind, across all themes. Not sure what's supposed to make this different. In any case, this should be fixed in  fe4a9b4e4b16a3272b295cb23bd262ce84284062.

**Closed by hlissner** 2023-12-02 17:06 UTC
Labels: duplicate

**Comment by jabotz** [comment] 2023-12-02 18:07
Sorry, I've now realised that `melpa` doesn't have the most recent commit. Will wait for its upload.
