### ISSUE TITLE
The background transparent image is not displayed properly

### ISSUE THREAD

**Issue by Hxppdv** [doomemacs/themes#728] opened 2022-05-22 09:49 UTC
### Theme(s)

doom-one

### What were you expecting?

The background color of the picture with transparent background should be the same as the background color of emacs (because the background of the picture is transparent)
![image](https://user-images.githubusercontent.com/17672838/169688849-8e8a207b-8df4-4afc-b754-2b2d66c4fbee.png)

### What actually happened?

In the doom-one theme, the background of the transparent image becomes some kind of brown
![image](https://user-images.githubusercontent.com/17672838/169688875-fbe0bd39-7d3d-4d6b-ac99-a45f1fc1f4f1.png)

I've tested many themes
doom-one-light    works
doom-1337           works
doom-acario-dark doesn't work
doom-acario-light doesn't work
doom-ayu-mirage doesn't work
doom-ayu-light     works
doom-horizon       doesn't work
doom-opera-light works
doom-opera          doesn't work
doom-sourcerer    works
doom-peacock      doesn't work
doom-plain-dark   works
doom-gruvbox      works

I hope this information is helpful
### Steps to reproduce

1. open emacs
2. Insert a image with a transparent background

### Operating system

Windows 10

### Emacs version

Emacs 28.1

### Installed commit of doom-themes

e9bdd137116fa2037ed60037b8421cf68c64888d

**Comment by hlissner** [comment] 2022-05-26 23:37
I cannot reproduce this with a transparent png or svg. I could go out of my way to enable [solaire-mode](https://github.com/hlissner/emacs-solaire-mode) in the wrong buffers (which changes the buffer's background) to recreate the effect, but the issue goes away when I re-insert the image (as expected).

doom-one (with solaire-mode off):
![image](https://user-images.githubusercontent.com/510883/170595756-365880bf-cd01-4a1b-a240-d1dc5d14d810.png)

doom-one (with solaire-mode on):
![image](https://user-images.githubusercontent.com/510883/170595818-6d44c191-d596-4e89-8420-bdb9c2d41804.png)

doom-one (with solaire-mode on, after I re-insert the image):
![image](https://user-images.githubusercontent.com/510883/170595876-2cd821d6-1ef2-4d9f-8172-5568e4478017.png)

As this doesn't seem like a theme issue (and I cannot investigate further without more information) I will close it, but feel free to follow up here.

**Closed by hlissner** 2022-05-26 23:37 UTC
Labels: invalid

**Comment by Hxppdv** [comment] 2022-07-19 07:03
@hlissner Sorry for the late reply, I don't know why you can't reproduce this issue, I tried the official build of emacs 28.1 and even tried emacs 29. but the issue still persists, I run emacs with emacs -Q every time I test so I can be sure it's not a problem with other packages. Maybe this bug only exists on windows? I hope this information helps, by the way the svg file I used for testing is attached.
![example](https://user-images.githubusercontent.com/17672838/179686805-f6f1fec3-b965-429a-8f19-674953cbcb90.svg)
![EmacsIcon](https://user-images.githubusercontent.com/17672838/179686906-0e9f7cad-90a6-4a57-95b8-7a34aa86d399.svg)
